version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: freterapido
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
    ports:
      - "5432:5432"
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d   # note o caminho relativo!

  api:
    build:
      context: ..      # sobe para raiz, onde está o Dockerfile
      dockerfile: Dockerfile
    command: [ "./yourbinary" ]
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env.development
    depends_on:
      - db
    restart: on-failure
